spring.application.name=hestiaBackEnd
spring.datasource.url=jdbc:postgresql://localhost:5432/hestia_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
springdoc.swagger-ui.disable-swagger-default-url=true
spring.security.filter.order=10
logging.level.org.springframework.security=DEBUG