spring.application.name=hestiaBackEnd
spring.datasource.url=jdbc:postgresql://localhost:6767/hestia_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
springdoc.swagger-ui.disable-swagger-default-url=true
spring.security.filter.order=10
logging.level.org.springframework.security=DEBUG
jwt.secret=809a3ece8801ead75261a57995aff18722a652626cf460628dfb34f4fc53a260